### ISSUE TITLE
Would you make OpenSim better with this project ?

### ISSUE THREAD

**Issue by BogusCurry** [emperorstarfinder/Opensim2#1]
Hello ;D

Would you make OpenSim better with this project ?

Greetings

Bogus

**Comment by emperorstarfinder** [comment]
Hey Bogus,

This was just for me to play around with Opensim and get ideas for Virtual Universe (and my main grid architecture) but if people want me to create something more modern and better with the Opensim code I am willing to give it a try.

**Comment by BogusCurry** [comment]
Hey ;D The sounds like good ;D I will test when time is it ;D

**Comment by emperorstarfinder** [comment]
You can always test at any time.  and even create feature requests etc.  ideas always a good thing.  If I get enough people asking ill just create a new organization separate from my normal work for it.

**Comment by BogusCurry** [comment]
OK I have test the source, run under Ubuntu 14.04 64-bit, Mono 4.4.1. Run so fine, but I can't see water. Is that a new feature ? *g

**Comment by emperorstarfinder** [comment]
Hmmm... Might be a bug as I havent even started working on any actual changes yet.  Can you send a picture of what your seeing? and does the consoles say anything about a missing texture?

**Comment by emperorstarfinder** [comment]
Going to close as user has not indicated a further issue.  As always feel free to open new issues as they arise.
